---
# Define architecture
arch_map:
  x86_64: amd64
  aarch64: arm64
app_arch: "{{ arch_map[ansible_architecture] | default(ansible_architecture) }}"
download_url: https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/{{ app_arch }}

# Docker package versions
containerd: containerd.io_1.7.23-1_amd64.deb
docker_ce: docker-ce_27.3.1-1~ubuntu.22.04~jammy_amd64.deb
docker_ce_cli: docker-ce-cli_27.3.1-1~ubuntu.22.04~jammy_amd64.deb
docker_compose: docker-compose-plugin_2.6.0~ubuntu-jammy_amd64.deb
docker_buildx: docker-buildx-plugin_0.17.1-1~ubuntu.22.04~jammy_amd64.deb

# Directory for storing downloaded files
download_dir: /tmp/docker_packages
