---
- name: Initialize Swarm Manager
  hosts: manager
  become: true
  tasks:
    - name: Run Swarm Init
      ansible.builtin.include_role:
        name: swarm
        tasks_from: init

- name: Join Workers to Swarm
  hosts: workers
  become: true
  tasks:
    - name: Run Swarm Join
      ansible.builtin.include_role:
        name: swarm
        tasks_from: join
