---
- name: Setup Operating System (Full)
  hosts: os
  become: true
  tasks:
    - name: Install Common Libs
      ansible.builtin.include_role:
        name: os
        tasks_from: libs
      tags: libs

    - name: Configure SSH Security
      ansible.builtin.include_role:
        name: os
        tasks_from: ssh
      tags: ssh

    - name: Configure Power Management
      ansible.builtin.include_role:
        name: os
        tasks_from: power
      tags: power
