---
- name: Uninstall Docker Engine
  hosts: docker
  become: true
  tasks:
    - name: Run Docker Uninstallation
      ansible.builtin.include_role:
        name: docker
        tasks_from: uninstall
