---
# Uninstall Docker
- name: Stop Docker Service
  ansible.builtin.service:
    name: docker
    state: stopped
  ignore_errors: true

- name: Remove Docker Packages (Ubuntu/Debian)
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: absent
    autoremove: true
  when: ansible_os_family == "Debian"

- name: Remove Docker Packages (RHEL/CentOS)
  ansible.builtin.dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: absent
    autoremove: true
  when: ansible_os_family == "RedHat"

- name: Remove Docker Data (Images, Containers, Volumes)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/docker
    - /var/lib/containerd
    - /etc/docker
    - /var/run/docker.sock

- name: Verify Docker is Removed
  ansible.builtin.command: docker --version
  register: docker_check
  ignore_errors: true
  changed_when: false

- name: Display Docker Removal Status
  ansible.builtin.debug:
    msg: Docker has been successfully removed
  when: docker_check.rc != 0
